### PR TITLE
Fix(autocomplete): Do not allow new values if not free solo

### LINKED ISSUE #2652: Admin > configuration d'un champ : Quand la "proposition d'une nouvelle valeur" dans une liste est désactivée, il est quand même possible en front de soumettre une nouvelle valeur, alors que ça ne devrait pas

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #2652

### CODE REVIEW

File: src/app/js/annotation/fields/ProposedValueFieldList.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ export function ProposedValueFieldList({
                 label={label}
                 options={options}
                 required
+                freeSolo={supportsNewValues}
```
Comment (ThieryMichel) [inline src/app/js/annotation/fields/ProposedValueFieldList.js]: freeSolo is not very explicit, how about:
```suggestion
                supportsNewValues={supportsNewValues}
```

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
