### PR TITLE
Fix(enrichment): Add confirm modal and better error handling when running all enrichments

### LINKED ISSUE #2186: (1) Lancer en 1 clic une liste d'enrichissements
### Discussed in https://github.com/Inist-CNRS/lodex/discussions/2019

<div type='discussions-op-text'>

<sup>Originally posted by **camilledesalabert** June  3, 2024</sup>
L'idée serait de pouvoir lancer en 1 action unique une longue liste d'enrichissements (cas d'usage : import d'un modèle sur un nouveau corpus et besoin de relancer tous les enrichissements sans qu'il soit nécessaire de les modifier)</div>

### LINKED ISSUE #2300: (Chore : 0,5) Relancer les enrichissements qui n'ont pas fonctionnés à cause des dépendances
Suite de la carte [2186](https://github.com/orgs/Inist-CNRS/projects/2/views/1?pane=issue&itemId=83465868&issue=Inist-CNRS%7Clodex%7C2186) 

**Contexte**
Lorsque je clique sur "Tout lancer", les enrichissements basés sur des colonnes qui n'ont pas encore été créées sont en erreur. Je dois alors relancer les enrichissement en Erreur un à un.

**Solution**
Au clic sur "Tout lancer", lancer les enrichissements un à un. A la fin de la liste, relancer les enrichissements en erreur

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #2186 
Closes #2300 

https://github.com/user-attachments/assets/52f01fb9-b055-45e6-8307-1cf6c7dec162

### CODE REVIEW

File: src/app/js/admin/enrichment/EnrichmentList.js [hunk 1]
```diff
@@ -1,76 +1,119 @@
...
+                    </Button>
+                    <Button
+                        onClick={handleLaunchAllEnrichment}
+                        variant="contained"
+                        color="primary"
+                    >
+                        {polyglot.t('run_all')}
+                    </Button>
+                </DialogActions>
+            </Dialog>
```
Comment (ThieryMichel) [inline src/app/js/admin/enrichment/EnrichmentList.js]: How about using the ConfirmPopup component instead?

File: src/app/js/admin/enrichment/sagas.js [hunk 2]
```diff
@@ -39,13 +43,33 @@ export function* handleLaunchEnrichment({ payload: enrichment }) {
...
+        const { error } = yield call(fetchSaga, enrichmentLaunchAllRequest);
+
+        if (error) {
+            const state = yield select();
+            const polyglot = getP(state);
+
+            if (error.message === 'circular_dependency_error') {
+                toast(polyglot.t('run_all_enrichment_circular_dependency'), {
+                    type: toast.TYPE.ERROR,
+                });
```
Comment (ThieryMichel) [inline src/app/js/admin/enrichment/sagas.js]: You should use yield call instead, no function with side effect should get called directly in a saga.
```suggestion
                yield call(
                    toast,
                    polyglot.t('run_all_enrichment_circular_dependency'),
                    { type: toast.TYPE.ERROR }
                );
```

File: src/app/js/admin/enrichment/sagas.js [hunk 3]
```diff
@@ -39,13 +43,33 @@ export function* handleLaunchEnrichment({ payload: enrichment }) {
...
+            } else {
+                toast(polyglot.t('run_all_enrichment_failed'), {
```
Comment (ThieryMichel) [inline src/app/js/admin/enrichment/sagas.js]: same

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
