### PR TITLE
Fix(facets): Clear facets filters when reseting the form

### LINKED ISSUE #2130: (0,5) [14.0.57]Filtre par facette ne fonctionne pas quand on ne se trouve pas sur la première partie de la liste
**Décrire le bogue**
Quand on recherche un terme dans une facette à partir de la deuxième liste de mots, la recherche ne fonctionne pas

**Reproduire**
Étapes pour reproduire le comportement :

1. Allez à ['...'](http://192.168.31.148:49268/instance/anftdm-biodiversite/)
2. Cliquez sur Recherche
3. Faites défiler l'écran jusqu'à la facette Pays nettoyés ou paysCorr_addressSplit
4. Cliquez sur la flèche pour accéder à la suite de la liste des termes, saisir France, aucune valeur n'apparaît

**Comportement attendu**
Pouvoir faire une recherche dans une facette, même quand on ne se trouve pas sur la première partie de la liste des termes

**Environnement (veuillez compléter les informations suivantes) :**

- Navigateur [Mozilla]

- Version de LODEX [14.0.57]

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #2130 

https://github.com/user-attachments/assets/c24093ee-2ab4-44f9-9cde-8eb86437745c

### CODE REVIEW

File: src/app/js/public/facet/sagas.js [hunk 1]
```diff
@@ -20,6 +20,26 @@ export default ({ actionTypes, actions, selectors }) => {
...
+        for (const name of Object.keys(facetsValues)) {
+            yield put(
+                actions.changeFacetValue({
+                    name,
+                    perPage: facetsValues[name].perPage,
+                    currentPage: 0,
+                    filter: '',
+                }),
+            );
+        }
```
Comment (ThieryMichel) [inline src/app/js/public/facet/sagas.js]: You can use yield all instead:
```js
yield all(Object.keys(facetsValues).map(name => put(... name ...)))
```

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
