### PR TITLE
Fix(annotation): Provide the ability to filter by home page and graph page

### LINKED ISSUE #2515: (0,5) Admin : Filtrer par "Page d'accueil" ou "Page graphique"
Suite au commentaire dans la [carte 2488](https://github.com/orgs/Inist-CNRS/projects/2/views/1?filterQuery=-status%3A%22Done+sprint+1%22%2C%22Done+sprint+2%22%2C%22Done+sprint+3%22&pane=issue&itemId=96475800&issue=Inist-CNRS%7Clodex%7C2488)

### Problème
Le filtre de la colonne URI fonctionne sur les URI des ressources et sous-ressources, mais ne fonctionne pas sur les valeur "Page d'accueil" et "Page graphique"

Image

Image

### Solution 
Dans le tableau des annotations : 
- Remplacer "Page 'accueil" par "/"
- "Page 'graphique" -> /graph/YTRU

Rendre fonctionnel le filtre sur la colonne "Uri" avec un opérateur "contient"
Ajouter un opérateur Exact, pour chercher les page d'accueil

Tests
- Les annotations soumises avant cette carte ne pourront pas être filtrable

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #2515

### CODE REVIEW

File: src/app/js/admin/annotations/details/AnnotationHeader.js [hunk 1]
```diff
@@ -7,48 +7,51 @@ import PropTypes from 'prop-types';
...
 };
 
 export function AnnotationHeader({ annotation }) {
     const { translate } = useTranslate();
 
     const { subtitle, linkUrl } = useMemo(() => {
-        if (annotation.field?.scope === 'graphic') {
+        const { resourceUri, field } = annotation;
+
+        if (getResourceType(resourceUri, field) === 'graph') {
```
Comment (ThieryMichel) [inline src/app/js/admin/annotations/details/AnnotationHeader.js]: Nitpick: can you call the function only once ?

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
