### PR TITLE
Fix(subresource): Add back button for ark resources

### LINKED ISSUE #2162: (Chore : 0,5) Retour sous-ressource/ressource dans le cas des ARK
Dans le cas des d’un corpus comportant des sous-ressources, le lien de retour d’une sous-ressource vers une ressource ne s’affiche plus si les ressources sont identifiées par un ARK et non un uid.

Lien vers la carte :https://trello.com/c/fpZvkbuI/375-retour-sous-ressource-ressource-dans-le-cas-des-ark

Attachements: image

**Comment reproduire ?**
Cliquer sur "Recherche" > ouvrir une ressource  > cliquer sur le lien d'une sous-ressource ( "Noms d’espèces détectées" )

1. Instance qui fonctionne (UIDS) : https://lodex-dev.inist.fr/instance/animalia/
En bas de la page un bouton "Retourner à la ressource" s'affiche automatiquement permettant de retourner à la ressource principale (les URIs se basent sur les UIDs)

2. Instance qui ne fonctionne pas (ARKs) : https://lodex-dev.inist.fr/instance/test-sous-ressources/
Le bouton "Retourner à la ressource" ne s'affiche pas (il faut ajouter manuellement un bouton de retour via une ressource formatée en HTML), les URIs se basent sur les identifiants ARKs.

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #2162

### CODE REVIEW

File: src/test-utils.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import React from 'react';
 import { render } from '@testing-library/react';
+import '@testing-library/jest-dom/extend-expect';
```
Comment (ThieryMichel) [inline src/test-utils.js:3]: :+1:

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
